=== oljamiljatovic/XML-projekat/xml project/ant/data/address_book4.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" version="1.0" targetNamespace="http://www.ftn.uns.ac.rs/jaxb/example4" xmlns:adr="http://www.ftn.uns.ac.rs/jaxb/example4" xmlns:tns="http://www.ftn.uns.ac.rs/jaxb/example4" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="address_book">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="contacts" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="contact" type="tns:personType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="person" type="tns:personType"/>

  <xs:complexType name="addressType">
    <xs:sequence>
      <xs:element name="country" type="xs:string" minOccurs="0"/>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="street" type="xs:string"/>
      <xs:element name="number" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="personType">
    <xs:sequence>
      <xs:element name="birth_date" type="xs:date" minOccurs="0"/>
      <xs:element name="phone" type="xs:string" maxOccurs="unbounded"/>
      <xs:element name="home_address" type="tns:addressType"/>
      <xs:element name="office_address" type="tns:addressType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="first_name" type="xs:string" use="required"/>
    <xs:attribute name="last_name" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== oljamiljatovic/XML-projekat/xml project/ant/data/address_book.xml
<?xml version="1.0" encoding="UTF-8"?>
<address_book xmlns="http://www.ftn.uns.ac.rs/jaxb/example4"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ftn.uns.ac.rs/jaxb/example4 address_book4.xsd">
	<name>My Address Book</name>
	<contacts>
		<contact first_name="Petar" last_name="Petrović">
			<birth_date>1967-08-13</birth_date>
			<phone>222-111</phone>
			<phone>111-222</phone>
			<home_address>
				<city>Novi Sad</city>
				<street>Fruškogorska</street>
				<number>11</number>
			</home_address>
			<office_address>
				<country>Serbia</country>
				<city>Novi Sad</city>
				<street>Trg D. Obradovića</street>
				<number>6</number>
			</office_address>
		</contact>
		<contact first_name="Jelena" last_name="Ninković">
			<birth_date>1947-01-12</birth_date>
			<phone>333-111</phone>
			<phone>333-222</phone>
			<home_address>
				<city>Novi Sad</city>
				<street>Rumenačka</street>
				<number>99</number>
			</home_address>
		</contact>
	</contacts>
</address_book>
