=== oljamiljatovic/XML-projekat/xml project/ant/data/depositSlip.xsd
<?xml version="1.0" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="depositSlip" type="DepositSlip"/>
    <xs:complexType name="DepositSlip">
        <xs:sequence>
            <xs:element name="deptor" type="xs:string"/>
            <xs:element name="receiver" type="xs:string"/>
            <xs:element name="purposeOfPayment" type="xs:string"/>
            <xs:element name="currencyDate" type="xs:date"/>
            <xs:element name="depositSlipDate" type="xs:date"/>
            <xs:element name="billOfDeptor" type="xs:string"/>
            <xs:element name="modelAssignment" type="xs:int"/>
            <xs:element name="referenceNumberAssignment" type="xs:string"/>
            <xs:element name="billOfReceiver" type="xs:string"/>
            <xs:element name="modelApproval" type="xs:int"/>
            <xs:element name="referenceNumberApproval" type="xs:string"/>
            <xs:element name="amount" type="xs:double"/>
            <xs:element name="codeOfCurrency" type="xs:string"/>
            <xs:element name="urgently" type="xs:boolean"/>
            <xs:element name="direction" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    
       
</xs:schema>

=== oljamiljatovic/XML-projekat/xml project/src/main/java/com/example/demo/depositSlip.xml
<?xml version="1.0" encoding="UTF-8"?>
<depositSlip  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="depositSlip.xsd">
    
    <id>5244</id>
    <deptor>Olja Miljatovic</deptor>
    <receiver>Vladimir Stanojevic</receiver>
    <purposeOfPayment>Uplata na racun</purposeOfPayment>
    <currencyDate>2002-09-24</currencyDate>
    <depositSlipDate>2002-09-24</depositSlipDate>
    <billOfDeptor>125896325475821458</billOfDeptor>
    <modelAssignment>12566</modelAssignment>
    <referenceNumberAssignment>12589632547582145858</referenceNumberAssignment>
    <billOfReceiver>125896325475821458</billOfReceiver>
    <modelApproval>30</modelApproval>
    <referenceNumberApproval>12589632547582145852</referenceNumberApproval>
    <amount>1256.36</amount>
    <codeOfCurrency>rsd</codeOfCurrency>
    <urgently>true</urgently>
    <direction>true</direction>
  
</depositSlip>
