=== oljamiljatovic/XML-projekat/xml project/ant/data/mt900.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mt900">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="idPoruke" type="Str50"/>
                <xs:element name="swiftKodBankeDuznika" type="Str8"/>
                <xs:element name="obracunskiRacunBankeDuznika" type="Str20"/>
                <xs:element name="idPorukeNaloga" type="Str50"/>
                <xs:element name="datumValute" type="xs:date"/>
                <xs:element name="iznos" type="Decimal15-2"/>
                <xs:element name="sifraValute" type="Str3"/>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
 
    <xs:simpleType name="Decimal15-2">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="15"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType> 

    
    <xs:simpleType name="Str50">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Str20">
        <xs:restriction base="xs:string">
            <xs:minLength value="20"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Str8">
        <xs:restriction base="xs:string">
            <xs:minLength value="8"/>
            <xs:maxLength value="8"/>
        </xs:restriction>
    </xs:simpleType>
    

    
    <xs:simpleType name="Str3">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="3"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== oljamiljatovic/XML-projekat/xml project/ant/data/mt900.xml
<?xml version="1.0" encoding="UTF-8"?>
<mt900  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="mt900.xsd">
    <idPoruke>id poruke 1</idPoruke>
    <swiftKodBankeDuznika>88888888</swiftKodBankeDuznika> 
    <obracunskiRacunBankeDuznika>20202020202020202020</obracunskiRacunBankeDuznika>
    <idPorukeNaloga>idMT103</idPorukeNaloga> 
    <datumValute>2002-09-24</datumValute>
    <iznos>16.20</iznos>
    <sifraValute>rsd</sifraValute>
</mt900>
