=== oljamiljatovic/XML-projekat/xml project/ant/data/nalog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="nalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="idPoruke" type="Str50"/>
                <xs:element name="duznik" type="Str255"/>
                <xs:element name="svrhaPlacanja" type="Str255"/>
                <xs:element name="primalac" type="Str255"/>
                <xs:element name="datumNaloga" type="xs:date"/>
                <xs:element name="datumValute" type="xs:date"/>
                <xs:element name="racunDuznika" type="Str18"/>
                <xs:element name="modelZaduzenja" type="Number2"/>
                <xs:element name="pozivNaBrojZaduzenja" type="Number20"/>
                <xs:element name="racunPrimaoca" type="Str18"/>
                <xs:element name="modelOdobrenja" type="Number2"/>
                <xs:element name="pozivNaBrojOdobrenja" type="Number20"/>
                <xs:element name="iznos" type="Decimal5-2"/>
                <xs:element name="oznakaValute" type="Str3"/>
                <xs:element name="hitno" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="Number20">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{20}"/>
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:simpleType name="Number2">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{2}"/>
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:simpleType name="Decimal5-2">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="5"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType> 
    
    <xs:simpleType name="Str255">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="255"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Str50">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="Str18">
        <xs:restriction base="xs:string">
            <xs:minLength value="18"/>
            <xs:maxLength value="18"/>
        </xs:restriction>
    </xs:simpleType>
   
    <xs:simpleType name="Str3">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
            <xs:maxLength value="3"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== oljamiljatovic/XML-projekat/xml project/ant/data/nalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<nalog  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="nalog.xsd">
    <idPoruke>poruka broj 1</idPoruke> 
    <duznik>Duznik 1</duznik>
    <svrhaPlacanja>placanje 1</svrhaPlacanja>
    <primalac>Primalac 1</primalac>
    <datumNaloga>2002-09-24</datumNaloga>
    <datumValute>2002-09-24</datumValute>
    <racunDuznika>181818181818181818</racunDuznika>
    <modelZaduzenja>97</modelZaduzenja>
    <pozivNaBrojZaduzenja>20202020202020202020</pozivNaBrojZaduzenja>
    <racunPrimaoca>771812281818181228</racunPrimaoca>
    <modelOdobrenja>97</modelOdobrenja>
    <pozivNaBrojOdobrenja>45454545454545454522</pozivNaBrojOdobrenja>
    <iznos>17.2</iznos>
    <oznakaValute>rsd</oznakaValute>
    <hitno>true</hitno>
    
</nalog>
