=== oljamiljatovic/XML-projekat/xml project/ant/data/univerzitet1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.ftn.uns.ac.rs/jaxb/example1"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.ftn.uns.ac.rs/jaxb/example1" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:element name="fakultet">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="odsek" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="studenti">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="student" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
												<xs:element name="polozenIspit" minOccurs="0"
												maxOccurs="unbounded">
												<xs:complexType>
												<xs:sequence>
												<xs:element name="predmet" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="ocena" type="xs:short"
												use="required"/>
												<xs:attribute name="datum" type="xs:date"
												use="required"/>
												<xs:attribute name="nastavnik" type="xs:string"
												use="required"/>
												</xs:complexType>
												</xs:element>
												</xs:sequence>
												<xs:attribute name="brojIndeksa" type="xs:int"
												use="required"/>
												<xs:attribute name="ime" type="xs:string"
												use="required"/>
												<xs:attribute name="prezime" type="xs:string"
												use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="naziv" type="xs:string" use="required"/>
						<xs:attribute name="id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="naziv" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== oljamiljatovic/XML-projekat/xml project/ant/data/univerzitet1.xml
<?xml version="1.0" encoding="UTF-8"?>
<fakultet xmlns="http://www.ftn.uns.ac.rs/jaxb/example1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ftn.uns.ac.rs/jaxb/example1 univerzitet1.xsd" naziv="FTN">
	<odsek id="21" naziv="Racunarstvo">
		<studenti>
			<student ime="Marko" prezime="Petrovic" brojIndeksa="7985">
				<polozenIspit ocena="10" nastavnik="Mirko Mirokovic" datum="2015-09-14">
					<predmet>Analiza 1</predmet>
				</polozenIspit>
			</student>
			<student ime="Jelena" prezime="Ninkovic" brojIndeksa="8024">
				<polozenIspit ocena="9" nastavnik="Mira Mirkovic" datum="2014-05-11">
					<predmet>Programiranje 2</predmet>
				</polozenIspit>
			</student>
		</studenti>
	</odsek>
	<odsek id="22" naziv="Menadzment">
		<studenti>
			<student ime="Sandra" prezime="Petrovic" brojIndeksa="3651">
				<polozenIspit ocena="8" nastavnik="Stevan Steovic" datum="2016-01-21">
					<predmet>Upravljanje 1</predmet>
				</polozenIspit>
			</student>
			<student ime="Jelena" prezime="Ninkovic" brojIndeksa="8024">
				<polozenIspit ocena="9" nastavnik="Draga Simic" datum="2016-01-22">
					<predmet>Strategija 1</predmet>
				</polozenIspit>
			</student>
		</studenti>
	</odsek>
</fakultet>
